EPSILON = 1e-6
MIN_CUBE_SIZE = 0.01
ZERO_THICKNESS_DIMENSION_RATIO = 0.05
ZERO_THICKNESS_MIN_PLANE_DIMENSION = MIN_CUBE_SIZE * 8.0
DEFAULT_COMPLEX_SPLIT_BONE = "head"

QUALITY_LARGEST_CUBES_LIMIT = 10
QUALITY_TINY_FRAGMENT_CUBES_LIMIT = 20
QUALITY_ELONGATED_DIMENSION_RATIO = 6.0
QUALITY_TINY_FRAGMENT_MAX_FACES = 2
AUTO_SPATIAL_SPLIT_OWNER_BUDGET_MULTIPLIER = 2
